"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const react_1 = __importDefault(require("react"));
require("./DocsStyles.css");
function DocsContainer() {
    return (react_1.default.createElement("div", { className: 'github' },
        react_1.default.createElement("h2", { id: 'section-title' }, "Docs"),
        react_1.default.createElement("a", { href: 'https://github.com/oslabs-beta/EmberQL#readme', className: 'link' }, "Explore Our Github"),
        react_1.default.createElement("div", { className: 'html' },
            react_1.default.createElement("h1", { id: "emberql" }, "EmberQL"),
            react_1.default.createElement("p", null,
                react_1.default.createElement("a", { href: "https://github.com/oslabs-beta/EmberQL/blob/dev/LICENSE" },
                    react_1.default.createElement("img", { src: "https://img.shields.io/badge/License-MIT-yellow.svg", alt: "License: MIT" }))),
            react_1.default.createElement("h2", { id: "what-is-emberql-" }, "What is EmberQL?"),
            react_1.default.createElement("p", null, "EmberQL is an intuitive, lightweight Node module that facilitates caching data from GraphQL queries, and implements a dynamic data persistence system that monitors the status of the primary database and modifies cache invalidation accordingly."),
            react_1.default.createElement("h2", { id: "features" }, "Features"),
            react_1.default.createElement("h3", { id: "server-side-caching-with-redis-to-decrease-query-times" }, "Server-side caching with Redis to decrease query times"),
            react_1.default.createElement("p", null, " Decrease the time it takes for your users to fetch data from your database by up to one hundred fold. Research shows that even a second of latency will drastically increase bounce rates on your application. Additionally, depending on the specifications or hosting of your database, too many simultaneous queries can cause timeouts to occur. Using EmberQL, there is no need to gamble with forcing your users to make redundant queries to your database."),
            react_1.default.createElement("h3", { id: "dynamic-cache-invalidation" }, "Dynamic cache invalidation"),
            react_1.default.createElement("p", null, " EmberQL incorporates a smart \"heartbeat\" feature that will monitor your database in real time and halt cache invalidation when it detects downtime. This is done by periodically increasing the time to live of cached data, and as soon as the database comes back online cached items will revert to being evicted normally. The heartbeat will communicate relevant information about the cache and database to the developer in the server console. "),
            react_1.default.createElement("h3", { id: "data-persistence-system-utilizing-rdb-redis-database-and-aof-append-only-file-" },
                "Data persistence system utilizing ",
                react_1.default.createElement("strong", null, "RDB"),
                " (Redis Database) and ",
                react_1.default.createElement("strong", null, "AOF"),
                " (Append Only File)"),
            react_1.default.createElement("p", null, " In the event of your database going down, the most relevant information users are querying will be available in the in-memory database and thus available to users. With EmberQL, there is no need for your clients to notice when your database isn't running. You can rest assured that your application will have fault tolerance after installing the module. "),
            react_1.default.createElement("h2", { id: "installation-prerequisites" }, "Installation & Prerequisites"),
            react_1.default.createElement("p", null, "Install the EmberQL module into your Node.js application by running the command npm install emberql. Your application must have GraphQL and as a dependency, and you will need to define your schema so that EmberQL can make use of it. You will also need Redis as a dependency to access the Redis functions (createClient, connect, on, etc.) and you will need to either run a Redis server on your machine locally or utilize AWS Elasticache to run a Redis server. "),
            react_1.default.createElement("h2", { id: "implementation" }, "Implementation"),
            react_1.default.createElement("p", null, "After installing, the module can be easily configured by making a few small additions to your server file. "),
            react_1.default.createElement("p", null, "The EmberQL class will take your GraphQL schema and your Redis cache instance as arguments:"),
            react_1.default.createElement("pre", null,
                react_1.default.createElement("code", null,
                    react_1.default.createElement("span", { class: "hljs-keyword" }, "const"),
                    " Ember = ",
                    react_1.default.createElement("span", { class: "hljs-keyword" }, "new"),
                    " EmberQL(schema, redisCache);")),
            react_1.default.createElement("p", null, "Any request sent to '/graphql' should be routed through the handleQuery middleware:"),
            react_1.default.createElement("pre", null,
                react_1.default.createElement("code", null,
                    "app.use(",
                    react_1.default.createElement("span", { class: "hljs-string" }, "'/graphql'"),
                    ", Ember.handleQuery, ",
                    react_1.default.createElement("span", { class: "hljs-function" },
                        react_1.default.createElement("span", { class: "hljs-params" }, "(req, res)"),
                        " =>"),
                    " ",
                    res.status(react_1.default.createElement("span", { class: "hljs-number" }, "202")).json(res.locals.data),
                    "; });")),
            react_1.default.createElement("p", null, "To clear the Redis cache, send a request to the '/clearCache' endpoint and route it through the EmberQL clearCache method:"),
            react_1.default.createElement("pre", null,
                react_1.default.createElement("code", null,
                    "app.use(",
                    react_1.default.createElement("span", { class: "hljs-string" }, "'/clearCache'"),
                    ", Ember.clearCache, ",
                    react_1.default.createElement("span", { class: "hljs-function" },
                        react_1.default.createElement("span", { class: "hljs-params" }, "(req, res)"),
                        " =>"),
                    " ",
                    res.sendStatus(react_1.default.createElement("span", { class: "hljs-number" }, "202")),
                    "; });")),
            react_1.default.createElement("p", null, "To set up the heartbeat, simply save the heartbeat property of the new EmberQL instance you just declared to a new variable. Then use the setInterval method and an interval of your choice to assign the frequency you would like the heartbeat to check your database:"),
            react_1.default.createElement("pre", null,
                react_1.default.createElement("code", null,
                    "const EmberHeartbeat = Ember.heartbeat; setInterval(",
                    react_1.default.createElement("span", { class: "hljs-function" },
                        react_1.default.createElement("span", { class: "hljs-params" }, "()"),
                        " =>"),
                    " ",
                    EmberHeartbeat(),
                    "; }, ",
                    react_1.default.createElement("span", { class: "hljs-number" }, "3000"),
                    ");")),
            react_1.default.createElement("h2", { id: "features-in-production" }, "Features in Production"),
            react_1.default.createElement("p", null, "Data normalization for Redis caching is currently in our development pipeline. The prototype utilizes a recursive function to parse the GraphQL AST and transform queries into key value pairs leveraging hashing to optimize memory. "),
            react_1.default.createElement("h2", { id: "emberql-engineering-team" }, "EmberQL Engineering Team"),
            react_1.default.createElement("p", null,
                react_1.default.createElement("a", { href: "https://github.com/Cristian-DeLosRios" }, "Cristian De Los Rios"),
                " |",
                react_1.default.createElement("a", { href: "https://github.com/manjunathap85" }, "Manjunath Ajjappa Pattanashetty"),
                " |",
                react_1.default.createElement("a", { href: "https://github.com/mikemasatsugu" }, "Mike Masatsugu"),
                " |",
                react_1.default.createElement("a", { href: "https://github.com/rammarimuthu" }, "Ram Marimuthu"),
                " |",
                react_1.default.createElement("a", { href: "https://github.com/tylerpohn" }, "Tyler Pohn")))));
}
exports.default = DocsContainer;
